package com.barbearia_api.service;

import com.barbearia_api.dto.usuario.UsuarioRegisterDto;
import com.barbearia_api.model.Usuario;
import com.barbearia_api.repositories.UsuarioRepository;
import com.barbearia_api.viewmodel.UsuarioVmGeral;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class UsuarioService {
    @Autowired
    private UsuarioRepository usuarioRepository;

    public List<UsuarioVmGeral> listAll(){
        return usuarioRepository.findAll().stream()
                .map(u -> new UsuarioVmGeral(u.getId(),u.getNome(), u.getEmail(), u.getTelefone(),u.getTipoPerfil()))
                .collect(Collectors.toList());
    }

    public UsuarioVmGeral listById(Integer id){
        return usuarioRepository.findById(id)
                .map(u -> new UsuarioVmGeral(u.getId(), u.getNome(), u.getEmail(), u.getTelefone(),u.getTipoPerfil()))
                .orElse(null);
    }

    public UsuarioVmGeral register(UsuarioRegisterDto usuarioRegisterDto){
        Usuario usuario = new Usuario(
                null, // id will be generated by the database
                usuarioRegisterDto.getNome(),
                usuarioRegisterDto.getEmail(),
                usuarioRegisterDto.getSenha(),
                usuarioRegisterDto.getTelefone(),
                Usuario.TipoPerfil.CLIENTE
        );

        usuario = usuarioRepository.save(usuario);

        return new UsuarioVmGeral(
                usuario.getId(),
                usuario.getNome(),
                usuario.getEmail(),
                usuario.getTelefone(),
                usuario.getTipoPerfil() // Include tipoPerfil in the response
        );
    }
}